export const EXAMPLE_PATH = 'helpdian'
export const CMS_NAME = 'Markdown'
export const HOME_OG_IMAGE_URL =
  'https://og-image.vercel.app/Next.js%20Blog%20Starter%20Example.png?theme=light&md=1&fontSize=100px&images=https%3A%2F%2Fassets.vercel.com%2Fimage%2Fupload%2Ffront%2Fassets%2Fdesign%2Fnextjs-black-logo.svg'
export const BLOG_NAME = 'Helpdian calculators'
export const KEYWORDS = 'calculators'
export const DESCRIPTION = 'Helpdian is wellbeing calculators and other calculators'
export const AUTHOR = 'helpdian desk'
export const LANG = 'en-US'
export const GITHUB_REPO = 'https://github.com/vdsd82'
